package com.bazl.hslims.webservice.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.11
 * 2017-05-11T15:08:53.239+08:00
 * Generated source version: 3.0.11
 * 
 */
@WebServiceClient(name = "Dna36DataWebServiceImplService", 
                  wsdlLocation = "http://localhost:8080/NationDnaWebService/ws/Dna36DataWebService?wsdl",
                  targetNamespace = "http://webservice.lims.bazl.com/") 
public class Dna36DataWebServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice.lims.bazl.com/", "Dna36DataWebServiceImplService");
    public final static QName Dna36DataWebServiceImplPort = new QName("http://webservice.lims.bazl.com/", "Dna36DataWebServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/NationDnaWebService/ws/Dna36DataWebService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Dna36DataWebServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/NationDnaWebService/ws/Dna36DataWebService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Dna36DataWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Dna36DataWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Dna36DataWebServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Dna36DataWebServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Dna36DataWebServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Dna36DataWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns Dna36DataWebService
     */
    @WebEndpoint(name = "Dna36DataWebServiceImplPort")
    public Dna36DataWebService getDna36DataWebServiceImplPort() {
        return super.getPort(Dna36DataWebServiceImplPort, Dna36DataWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Dna36DataWebService
     */
    @WebEndpoint(name = "Dna36DataWebServiceImplPort")
    public Dna36DataWebService getDna36DataWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(Dna36DataWebServiceImplPort, Dna36DataWebService.class, features);
    }

}
