package com.bazl.hslims.webservice.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.11
 * 2019-02-28T17:31:37.099+08:00
 * Generated source version: 3.0.11
 * 
 */
@WebService(targetNamespace = "http://service", name = "sceneManagerPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface SceneManagerPortType {

    @WebMethod(operationName = "GetTestResult")
    @RequestWrapper(localName = "GetTestResult", targetNamespace = "http://service", className = "com.bazl.hslims.webservice.client.GetTestResult")
    @ResponseWrapper(localName = "GetTestResultResponse", targetNamespace = "http://service", className = "com.bazl.hslims.webservice.client.GetTestResultResponse")
    @WebResult(name = "out", targetNamespace = "http://service")
    public java.lang.String getTestResult(
        @WebParam(name = "resultStr", targetNamespace = "http://service")
        java.lang.String resultStr
    );

    @WebMethod
    @RequestWrapper(localName = "queryData", targetNamespace = "http://service", className = "com.bazl.hslims.webservice.client.QueryData")
    @ResponseWrapper(localName = "queryDataResponse", targetNamespace = "http://service", className = "com.bazl.hslims.webservice.client.QueryDataResponse")
    @WebResult(name = "out", targetNamespace = "http://service")
    public java.lang.String queryData(
        @WebParam(name = "xmlString", targetNamespace = "http://service")
        java.lang.String xmlString,
        @WebParam(name = "isbase64", targetNamespace = "http://service")
        java.lang.Boolean isbase64
    );

    @WebMethod
    @RequestWrapper(localName = "queryIfExistIdentify", targetNamespace = "http://service", className = "com.bazl.hslims.webservice.client.QueryIfExistIdentify")
    @ResponseWrapper(localName = "queryIfExistIdentifyResponse", targetNamespace = "http://service", className = "com.bazl.hslims.webservice.client.QueryIfExistIdentifyResponse")
    @WebResult(name = "out", targetNamespace = "http://service")
    public java.lang.String queryIfExistIdentify(
        @WebParam(name = "xml", targetNamespace = "http://service")
        java.lang.String xml,
        @WebParam(name = "binaryData", targetNamespace = "http://service")
        byte[] binaryData
    );

    @WebMethod
    @RequestWrapper(localName = "querySceneInvestigationNoIfExists", targetNamespace = "http://service", className = "com.bazl.hslims.webservice.client.QuerySceneInvestigationNoIfExists")
    @ResponseWrapper(localName = "querySceneInvestigationNoIfExistsResponse", targetNamespace = "http://service", className = "com.bazl.hslims.webservice.client.QuerySceneInvestigationNoIfExistsResponse")
    @WebResult(name = "out", targetNamespace = "http://service")
    public java.lang.String querySceneInvestigationNoIfExists(
        @WebParam(name = "investigationNo", targetNamespace = "http://service")
        java.lang.String investigationNo
    );

    @WebMethod
    @RequestWrapper(localName = "deleteIdentifyById", targetNamespace = "http://service", className = "com.bazl.hslims.webservice.client.DeleteIdentifyById")
    @ResponseWrapper(localName = "deleteIdentifyByIdResponse", targetNamespace = "http://service", className = "com.bazl.hslims.webservice.client.DeleteIdentifyByIdResponse")
    @WebResult(name = "out", targetNamespace = "http://service")
    public java.lang.String deleteIdentifyById(
        @WebParam(name = "jd_id", targetNamespace = "http://service")
        java.lang.String jdId,
        @WebParam(name = "wzlb", targetNamespace = "http://service")
        java.lang.String wzlb
    );

    @WebMethod(operationName = "GetCaseInfo")
    @RequestWrapper(localName = "GetCaseInfo", targetNamespace = "http://service", className = "com.bazl.hslims.webservice.client.GetCaseInfo")
    @ResponseWrapper(localName = "GetCaseInfoResponse", targetNamespace = "http://service", className = "com.bazl.hslims.webservice.client.GetCaseInfoResponse")
    @WebResult(name = "out", targetNamespace = "http://service")
    public java.lang.String getCaseInfo(
        @WebParam(name = "k_id", targetNamespace = "http://service")
        java.lang.String kId
    );

    @WebMethod
    @RequestWrapper(localName = "extractSceneInfo", targetNamespace = "http://service", className = "com.bazl.hslims.webservice.client.ExtractSceneInfo")
    @ResponseWrapper(localName = "extractSceneInfoResponse", targetNamespace = "http://service", className = "com.bazl.hslims.webservice.client.ExtractSceneInfoResponse")
    @WebResult(name = "out", targetNamespace = "http://service")
    public java.lang.String extractSceneInfo(
        @WebParam(name = "para", targetNamespace = "http://service")
        java.lang.String para
    );

    @WebMethod
    @RequestWrapper(localName = "querySceneInfo", targetNamespace = "http://service", className = "com.bazl.hslims.webservice.client.QuerySceneInfo")
    @ResponseWrapper(localName = "querySceneInfoResponse", targetNamespace = "http://service", className = "com.bazl.hslims.webservice.client.QuerySceneInfoResponse")
    @WebResult(name = "out", targetNamespace = "http://service")
    public java.lang.String querySceneInfo(
        @WebParam(name = "para", targetNamespace = "http://service")
        java.lang.String para
    );

    @WebMethod
    @RequestWrapper(localName = "setContrastInfo", targetNamespace = "http://service", className = "com.bazl.hslims.webservice.client.SetContrastInfo")
    @ResponseWrapper(localName = "setContrastInfoResponse", targetNamespace = "http://service", className = "com.bazl.hslims.webservice.client.SetContrastInfoResponse")
    @WebResult(name = "out", targetNamespace = "http://service")
    public java.lang.String setContrastInfo(
        @WebParam(name = "xml", targetNamespace = "http://service")
        java.lang.String xml
    );

    @WebMethod
    @RequestWrapper(localName = "authorizeFeedback", targetNamespace = "http://service", className = "com.bazl.hslims.webservice.client.AuthorizeFeedback")
    @ResponseWrapper(localName = "authorizeFeedbackResponse", targetNamespace = "http://service", className = "com.bazl.hslims.webservice.client.AuthorizeFeedbackResponse")
    @WebResult(name = "out", targetNamespace = "http://service")
    public java.lang.String authorizeFeedback(
        @WebParam(name = "xml", targetNamespace = "http://service")
        java.lang.String xml
    );

    @WebMethod
    @RequestWrapper(localName = "feedbackConsignmentStatus", targetNamespace = "http://service", className = "com.bazl.hslims.webservice.client.FeedbackConsignmentStatus")
    @ResponseWrapper(localName = "feedbackConsignmentStatusResponse", targetNamespace = "http://service", className = "com.bazl.hslims.webservice.client.FeedbackConsignmentStatusResponse")
    @WebResult(name = "out", targetNamespace = "http://service")
    public java.lang.String feedbackConsignmentStatus(
        @WebParam(name = "para", targetNamespace = "http://service")
        java.lang.String para
    );

    @WebMethod
    @RequestWrapper(localName = "findSceneInvestigation", targetNamespace = "http://service", className = "com.bazl.hslims.webservice.client.FindSceneInvestigation")
    @ResponseWrapper(localName = "findSceneInvestigationResponse", targetNamespace = "http://service", className = "com.bazl.hslims.webservice.client.FindSceneInvestigationResponse")
    @WebResult(name = "out", targetNamespace = "http://service")
    public java.lang.String findSceneInvestigation(
        @WebParam(name = "investigation_no", targetNamespace = "http://service")
        java.lang.String investigationNo,
        @WebParam(name = "evi_type", targetNamespace = "http://service")
        java.lang.String eviType
    );

    @WebMethod
    @RequestWrapper(localName = "setBDXX", targetNamespace = "http://service", className = "com.bazl.hslims.webservice.client.SetBDXX")
    @ResponseWrapper(localName = "setBDXXResponse", targetNamespace = "http://service", className = "com.bazl.hslims.webservice.client.SetBDXXResponse")
    @WebResult(name = "out", targetNamespace = "http://service")
    public java.lang.String setBDXX(
        @WebParam(name = "strBDXX", targetNamespace = "http://service")
        java.lang.String strBDXX
    );

    @WebMethod(operationName = "GetCaseResult")
    @RequestWrapper(localName = "GetCaseResult", targetNamespace = "http://service", className = "com.bazl.hslims.webservice.client.GetCaseResult")
    @ResponseWrapper(localName = "GetCaseResultResponse", targetNamespace = "http://service", className = "com.bazl.hslims.webservice.client.GetCaseResultResponse")
    @WebResult(name = "out", targetNamespace = "http://service")
    public java.lang.String getCaseResult(
        @WebParam(name = "resultStr", targetNamespace = "http://service")
        java.lang.String resultStr
    );

    @WebMethod
    @RequestWrapper(localName = "feedbackConsignment", targetNamespace = "http://service", className = "com.bazl.hslims.webservice.client.FeedbackConsignment")
    @ResponseWrapper(localName = "feedbackConsignmentResponse", targetNamespace = "http://service", className = "com.bazl.hslims.webservice.client.FeedbackConsignmentResponse")
    @WebResult(name = "out", targetNamespace = "http://service")
    public java.lang.String feedbackConsignment(
        @WebParam(name = "para", targetNamespace = "http://service")
        java.lang.String para
    );

    @WebMethod(operationName = "GetCaseList")
    @RequestWrapper(localName = "GetCaseList", targetNamespace = "http://service", className = "com.bazl.hslims.webservice.client.GetCaseList")
    @ResponseWrapper(localName = "GetCaseListResponse", targetNamespace = "http://service", className = "com.bazl.hslims.webservice.client.GetCaseListResponse")
    @WebResult(name = "out", targetNamespace = "http://service")
    public java.lang.String getCaseList(
        @WebParam(name = "k_no", targetNamespace = "http://service")
        java.lang.String kNo,
        @WebParam(name = "scene_detail", targetNamespace = "http://service")
        java.lang.String sceneDetail,
        @WebParam(name = "k_user", targetNamespace = "http://service")
        java.lang.String kUser,
        @WebParam(name = "begin_time", targetNamespace = "http://service")
        java.lang.String beginTime,
        @WebParam(name = "end_time", targetNamespace = "http://service")
        java.lang.String endTime,
        @WebParam(name = "begin", targetNamespace = "http://service")
        java.lang.String begin,
        @WebParam(name = "end", targetNamespace = "http://service")
        java.lang.String end
    );

    @WebMethod
    @RequestWrapper(localName = "querySceneInvestigationInfo", targetNamespace = "http://service", className = "com.bazl.hslims.webservice.client.QuerySceneInvestigationInfo")
    @ResponseWrapper(localName = "querySceneInvestigationInfoResponse", targetNamespace = "http://service", className = "com.bazl.hslims.webservice.client.QuerySceneInvestigationInfoResponse")
    @WebResult(name = "out", targetNamespace = "http://service")
    public java.lang.String querySceneInvestigationInfo(
        @WebParam(name = "xml", targetNamespace = "http://service")
        java.lang.String xml
    );

    @WebMethod(operationName = "GetCaseListCount")
    @RequestWrapper(localName = "GetCaseListCount", targetNamespace = "http://service", className = "com.bazl.hslims.webservice.client.GetCaseListCount")
    @ResponseWrapper(localName = "GetCaseListCountResponse", targetNamespace = "http://service", className = "com.bazl.hslims.webservice.client.GetCaseListCountResponse")
    @WebResult(name = "out", targetNamespace = "http://service")
    public java.lang.String getCaseListCount(
        @WebParam(name = "k_no", targetNamespace = "http://service")
        java.lang.String kNo,
        @WebParam(name = "scene_detail", targetNamespace = "http://service")
        java.lang.String sceneDetail,
        @WebParam(name = "k_user", targetNamespace = "http://service")
        java.lang.String kUser,
        @WebParam(name = "begin_time", targetNamespace = "http://service")
        java.lang.String beginTime,
        @WebParam(name = "end_time", targetNamespace = "http://service")
        java.lang.String endTime
    );

    @WebMethod
    @RequestWrapper(localName = "findInvestigationNo", targetNamespace = "http://service", className = "com.bazl.hslims.webservice.client.FindInvestigationNo")
    @ResponseWrapper(localName = "findInvestigationNoResponse", targetNamespace = "http://service", className = "com.bazl.hslims.webservice.client.FindInvestigationNoResponse")
    @WebResult(name = "out", targetNamespace = "http://service")
    public java.lang.String findInvestigationNo(
        @WebParam(name = "reception_no", targetNamespace = "http://service")
        java.lang.String receptionNo,
        @WebParam(name = "case_no", targetNamespace = "http://service")
        java.lang.String caseNo
    );

    @WebMethod
    @RequestWrapper(localName = "validateKno", targetNamespace = "http://service", className = "com.bazl.hslims.webservice.client.ValidateKno")
    @ResponseWrapper(localName = "validateKnoResponse", targetNamespace = "http://service", className = "com.bazl.hslims.webservice.client.ValidateKnoResponse")
    @WebResult(name = "out", targetNamespace = "http://service")
    public java.lang.String validateKno(
        @WebParam(name = "para", targetNamespace = "http://service")
        java.lang.String para
    );
}
