package com.bazl.hslims.webservice.client;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.0.11
 * 2019-02-28T17:31:37.209+08:00
 * Generated source version: 3.0.11
 * 
 */
@WebServiceClient(name = "sceneManager", 
                  wsdlLocation = "http://10.160.121.186:9080/xckyservice/service/sceneManager?wsdl",
                  targetNamespace = "http://service") 
public class SceneManager extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service", "sceneManager");
    public final static QName SceneManagerHttpPort = new QName("http://service", "sceneManagerHttpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.160.121.186:9080/xckyservice/service/sceneManager?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SceneManager.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.160.121.186:9080/xckyservice/service/sceneManager?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SceneManager(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SceneManager(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SceneManager() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SceneManager(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SceneManager(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SceneManager(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns SceneManagerPortType
     */
    @WebEndpoint(name = "sceneManagerHttpPort")
    public SceneManagerPortType getSceneManagerHttpPort() {
        return super.getPort(SceneManagerHttpPort, SceneManagerPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SceneManagerPortType
     */
    @WebEndpoint(name = "sceneManagerHttpPort")
    public SceneManagerPortType getSceneManagerHttpPort(WebServiceFeature... features) {
        return super.getPort(SceneManagerHttpPort, SceneManagerPortType.class, features);
    }

}
