package com.bazl.hslims.webservice.client;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.0.11
 * 2018-07-26T15:11:12.463+08:00
 * Generated source version: 3.0.11
 * 
 */
@WebServiceClient(name = "sceneDnaManager", 
                  wsdlLocation = "http://211.157.146.6:8080/xckyservice/service/sceneDnaManager?wsdl",
                  targetNamespace = "http://service") 
public class SceneDnaManager extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service", "sceneDnaManager");
    public final static QName SceneDnaManagerHttpPort = new QName("http://service", "sceneDnaManagerHttpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://211.157.146.6:8080/xckyservice/service/sceneDnaManager?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SceneDnaManager.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://211.157.146.6:8080/xckyservice/service/sceneDnaManager?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SceneDnaManager(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SceneDnaManager(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SceneDnaManager() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SceneDnaManager(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SceneDnaManager(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SceneDnaManager(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns SceneDnaManagerPortType
     */
    @WebEndpoint(name = "sceneDnaManagerHttpPort")
    public SceneDnaManagerPortType getSceneDnaManagerHttpPort() {
        return super.getPort(SceneDnaManagerHttpPort, SceneDnaManagerPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SceneDnaManagerPortType
     */
    @WebEndpoint(name = "sceneDnaManagerHttpPort")
    public SceneDnaManagerPortType getSceneDnaManagerHttpPort(WebServiceFeature... features) {
        return super.getPort(SceneDnaManagerHttpPort, SceneDnaManagerPortType.class, features);
    }

}
