package com.bazl.hslims.webservice.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.11
 * 2018-07-26T15:11:12.391+08:00
 * Generated source version: 3.0.11
 * 
 */
@WebService(targetNamespace = "http://service", name = "sceneDnaManagerPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface SceneDnaManagerPortType {

    @WebMethod
    @RequestWrapper(localName = "fbEntrustStatus", targetNamespace = "http://service", className = "com.bazl.hslims.webservice.client.FbEntrustStatus")
    @ResponseWrapper(localName = "fbEntrustStatusResponse", targetNamespace = "http://service", className = "com.bazl.hslims.webservice.client.FbEntrustStatusResponse")
    @WebResult(name = "out", targetNamespace = "http://service")
    public java.lang.String fbEntrustStatus(
        @WebParam(name = "xmlStr", targetNamespace = "http://service")
        java.lang.String xmlStr
    );

    @WebMethod
    @RequestWrapper(localName = "updateToWZWTFK", targetNamespace = "http://service", className = "com.bazl.hslims.webservice.client.UpdateToWZWTFK")
    @ResponseWrapper(localName = "updateToWZWTFKResponse", targetNamespace = "http://service", className = "com.bazl.hslims.webservice.client.UpdateToWZWTFKResponse")
    public void updateToWZWTFK();

    @WebMethod
    @RequestWrapper(localName = "syncFeedbackInfo", targetNamespace = "http://service", className = "com.bazl.hslims.webservice.client.SyncFeedbackInfo")
    @ResponseWrapper(localName = "syncFeedbackInfoResponse", targetNamespace = "http://service", className = "com.bazl.hslims.webservice.client.SyncFeedbackInfoResponse")
    public void syncFeedbackInfo();

    @WebMethod
    @RequestWrapper(localName = "setBDXX", targetNamespace = "http://service", className = "com.bazl.hslims.webservice.client.SetBDXX")
    @ResponseWrapper(localName = "setBDXXResponse", targetNamespace = "http://service", className = "com.bazl.hslims.webservice.client.SetBDXXResponse")
    @WebResult(name = "out", targetNamespace = "http://service")
    public java.lang.String setBDXX(
        @WebParam(name = "xmlStr", targetNamespace = "http://service")
        java.lang.String xmlStr
    );

    @WebMethod
    @RequestWrapper(localName = "fbEvidenceStatus", targetNamespace = "http://service", className = "com.bazl.hslims.webservice.client.FbEvidenceStatus")
    @ResponseWrapper(localName = "fbEvidenceStatusResponse", targetNamespace = "http://service", className = "com.bazl.hslims.webservice.client.FbEvidenceStatusResponse")
    @WebResult(name = "out", targetNamespace = "http://service")
    public java.lang.String fbEvidenceStatus(
        @WebParam(name = "xmlStr", targetNamespace = "http://service")
        java.lang.String xmlStr
    );

    @WebMethod
    @RequestWrapper(localName = "insertToJCXXFKAndWZWTFK", targetNamespace = "http://service", className = "com.bazl.hslims.webservice.client.InsertToJCXXFKAndWZWTFK")
    @ResponseWrapper(localName = "insertToJCXXFKAndWZWTFKResponse", targetNamespace = "http://service", className = "com.bazl.hslims.webservice.client.InsertToJCXXFKAndWZWTFKResponse")
    public void insertToJCXXFKAndWZWTFK();

    @WebMethod
    @RequestWrapper(localName = "setWTZT", targetNamespace = "http://service", className = "com.bazl.hslims.webservice.client.SetWTZT")
    @ResponseWrapper(localName = "setWTZTResponse", targetNamespace = "http://service", className = "com.bazl.hslims.webservice.client.SetWTZTResponse")
    @WebResult(name = "out", targetNamespace = "http://service")
    public java.lang.String setWTZT(
        @WebParam(name = "xmlStr", targetNamespace = "http://service")
        java.lang.String xmlStr
    );

    @WebMethod
    @RequestWrapper(localName = "findAssignedContentByInvestigationId", targetNamespace = "http://service", className = "com.bazl.hslims.webservice.client.FindAssignedContentByInvestigationId")
    @ResponseWrapper(localName = "findAssignedContentByInvestigationIdResponse", targetNamespace = "http://service", className = "com.bazl.hslims.webservice.client.FindAssignedContentByInvestigationIdResponse")
    @WebResult(name = "out", targetNamespace = "http://service")
    public java.lang.String findAssignedContentByInvestigationId(
        @WebParam(name = "in0", targetNamespace = "http://service")
        java.lang.String in0
    );

    @WebMethod
    @RequestWrapper(localName = "getFeedbackInfo", targetNamespace = "http://service", className = "com.bazl.hslims.webservice.client.GetFeedbackInfo")
    @ResponseWrapper(localName = "getFeedbackInfoResponse", targetNamespace = "http://service", className = "com.bazl.hslims.webservice.client.GetFeedbackInfoResponse")
    public void getFeedbackInfo();

    @WebMethod
    @RequestWrapper(localName = "getSceneInvestigation", targetNamespace = "http://service", className = "com.bazl.hslims.webservice.client.GetSceneInvestigation")
    @ResponseWrapper(localName = "getSceneInvestigationResponse", targetNamespace = "http://service", className = "com.bazl.hslims.webservice.client.GetSceneInvestigationResponse")
    @WebResult(name = "out", targetNamespace = "http://service")
    public java.lang.String getSceneInvestigation(
        @WebParam(name = "xmlStr", targetNamespace = "http://service")
        java.lang.String xmlStr
    );
}
